### ISSUE TITLE
There should be a capability to delete / edit others comments

### ISSUE THREAD

**Issue by mudrd8mz** [safatshahin-dev/moodle-mod_debate#5]
Teachers and admins should have option to edit or delete others' comments.

**Comment by Dag-DE** [comment]
actual, there is the capability mod/debate:view

perhaps also good:

    writing (else guests can also write)
    writing out of debate "time"
    deleting responses (like moderation)

**Comment by mudrd8mz** [comment]
> else guests can also write

Oh, I haven't noticed this. Indeed - it's a general rule in Moodle. Non-authentic users should not be allowed to create any content or modify the database.

**Comment by safatshahin** [comment]
hi @mudrd8mz , adding delete seems like a very important feature, do you think edit should be there as well? having edit as a capability adds another concern about data integrity, where it has to record who updated it and need to show that information to the user as well, otherwise, it will introduce confusion.
I was thinking of implementing delete capability at this point, what do you think?

@Dag-EU  can you please explain a bit more about writing out of debate "time"? I believe I can not implement writing (else guests can also write) as David explained in his previous comment.

**Comment by mudrd8mz** [comment]
> I was thinking of implementing delete capability at this point

Yes, I agree. Editing is complicated in this case.

**Comment by safatshahin** [comment]
added capability for managers or teachers to delete responses also added the capabilities for users to edit their own response as well as delete their own response so that it can be handled via capability by admins.
also added events for every single action in debate activity. thanks a lot, @mudrd8mz  for your input in this.
